name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.x"
          
      - name: Debug - List directory structure
        run: |
          dir
          dir src

      - name: Build
        run: |
          cd src
          dotnet restore
          dotnet build --no-restore

      - name: Publish executable
        run: |
          cd src
          dotnet publish --configuration Release -r win-x64 --self-contained true /p:PublishSingleFile=true
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PublishedApp
          path: ./src/bin/Release/net7.0-windows/win-x64/publish/
